### ISSUE TITLE
can't get enough peer connections

### ISSUE THREAD

**Issue by g4bwy** [binance-chain/bsc-erigon#11]
Hi,

I just managed to sync up the chain's head on bsc mainnet (up to block 13750372), but apparently the node has a lot of trouble connecting to other peers. The maximum I got at any one time was 6 or 7 peers, while the default limit is 100.

When enabling traces I can see many messages like these:
```
[TRACE] [12-24|09:56:13.396] Adding p2p peer                          peercount=1 id=8256892f83de8394bb7dc2bb7bd10ce44dc5c7b5974f95099e14562983344a8b conn=staticdial addr=35.72.50.231:30311 name=Geth/v1.1.7-99cb655f...
[TRACE] [12-24|09:56:13.396] Starting protocol eth/66                 id=8256892f83de8394bb7dc2bb7bd10ce44dc5c7b5974f95099e14562983344a8b conn=staticdial
[TRACE] [12-24|09:56:13.396] [8256892f83de8394bb7dc2bb7bd10ce44dc5c7b5974f95099e14562983344a8b] Start with peer
[TRACE] [12-24|09:56:13.857] [8256892f83de8394bb7dc2bb7bd10ce44dc5c7b5974f95099e14562983344a8b] Received status message OK name=Geth/v1.1.7-99cb655f...
[TRACE] [12-24|09:56:13.858] [8256892f83de8394bb7dc2bb7bd10ce44dc5c7b5974f95099e14562983344a8b] Error while running peer: reading message: EOF
[TRACE] [12-24|09:56:13.858] Protocol eth/66 returned                 id=8256892f83de8394bb7dc2bb7bd10ce44dc5c7b5974f95099e14562983344a8b conn=staticdial
[TRACE] [12-24|09:56:13.858] Removing p2p peer                        peercount=0 id=8256892f83de8394bb7dc2bb7bd10ce44dc5c7b5974f95099e14562983344a8b duration=461.725ms req=false err="peer has: too many peers"
```

The logs and netstat indicate there are many attemps to connect, but most fail right after the handshake...

**Comment by havsar** [comment]
We noticed an issue with the peers when we ran on Debian.
Switched to Ubuntu and peers always stayed at 99.

**Comment by g4bwy** [comment]
well indeed I'm running debian unstable right now (with kernel 5.15.5-1)

**Comment by g4bwy** [comment]
looks like I have the same issue within a ubuntu impish lxc container, so I guess there might be something with the kernel or network sysctls

**Comment by g4bwy** [comment]
another intriguing behavior: sometimes the node manages to get 1 (or a few mores, but most often this is just one) peer connection, retrieves latest blocks and syncs up to the chain's head, then all connections get dropped immediately after the txpool starts

**Comment by gituser** [comment]
same issue I get like 1-2 peers max on erigon-bsc fork

**Comment by g4bwy** [comment]
> We noticed an issue with the peers when we ran on Debian. Switched to Ubuntu and peers always stayed at 99.

I'm still having this problem when running the p2p client directly from a debian 11 host with kernel 5.15.

However, if I forward all p2p traffic from a sentry daemon running on another debian with kernel 5.10, I manage to get between 95 and 99 peers at all times (however it took a while to reach that point, but it seems to be a known issue from upstream).

So the major differences I see between the two are the kernel version (5.10 versus 5.15), and the server's hoster: the one with the working daemon is at OVH (german datacenter) while the one which can't connect is at Hetzner (germany too).

What looks suspicous is that when running at hetzner, the p2p client is unable to detect its external IP address, and I need to use --nat:extip to avoid getting an enode string containing 127.0.0.1 instead of the real IP address.

**Comment by nikolinsko** [comment]
i seem to run into the same problem.

- server located at hetzner
- nat extip needed as above
- ports are forwarded correctly and reachable from the outside

**Comment by g4bwy** [comment]
I just started trying with your peers list and I can't get connections (yet).

even switching to the upstream [branch](https://github.com/ledgerwatch/erigon/pull/3233) doesn't seem to help with this issue.

I'll let it run for a while to see if the node starts getting some connections...

**Comment by dmitry123** [comment]
I had this issue several times, but after awaiting of ~1 hour node can establish connection to the peers. The issue might be somewhere in static node list or bootstrap list.

**Comment by g4bwy** [comment]
somehow it fell into place with using default port 30303 and switch to upstream ledgerwatch/erigon's devel branch (which now has  full bsc support merged).
